import { InjectQueue } from '@nestjs/bullmq';
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Queue } from 'bullmq';
import { Repository } from 'typeorm';
import { CreateTimbraturaDto } from './dto/create-timbratura.dto';
import { ListTimbratureDto } from './dto/list-timbrature.dto';
import {
  OrigineEnum,
  TimbraturaEntity,
  ValidityStatusEnum,
} from './entities/timbratura.entity';

@Injectable()
export class TimbratureService {
  constructor(
    @InjectQueue('timbrature')
    private readonly timbratureQueue: Queue,
    @InjectRepository(TimbraturaEntity)
    private readonly timbratureRepository: Repository<TimbraturaEntity>,
  ) {}

  async enqueueCreate(dto: CreateTimbraturaDto, idempotencyKey?: string) {
    const jobId = idempotencyKey ?? undefined;
    const job = await this.timbratureQueue.add(
      'create-timbratura',
      {
        ...dto,
        idempotencyKey,
      },
      {
        jobId,
        attempts: 5,
        backoff: {
          type: 'exponential',
          delay: 500,
        },
        removeOnComplete: false,
      },
    );

    return {
      status: 'accepted',
      jobId: job.id,
      queue: 'timbrature',
    };
  }

  async getJobStatus(jobId: string) {
    const job = await this.timbratureQueue.getJob(jobId);
    if (!job) throw new NotFoundException('Job not found');

    const state = await job.getState();
    return {
      jobId: job.id,
      state,
      attemptsMade: job.attemptsMade,
      result: (job.returnvalue as unknown) ?? null,
      failedReason: job.failedReason ?? null,
    };
  }

  async persistTimbratura(
    payload: CreateTimbraturaDto & { idempotencyKey?: string },
  ): Promise<TimbraturaEntity> {
    if (payload.idempotencyKey) {
      const existing = await this.timbratureRepository.findOne({
        where: { idempotencyKey: payload.idempotencyKey },
      });
      if (existing) return existing;
    }

    const timbratura = this.timbratureRepository.create({
      userId: payload.userId,
      commessaId: payload.commessaId,
      tipo: payload.tipo,
      deviceTimestamp: new Date(payload.deviceTimestamp),
      serverTimestamp: new Date(),
      origine: payload.origine ?? OrigineEnum.ONLINE,
      autoGenerated: false,
      validityStatus: ValidityStatusEnum.OK,
      anomalyFlags: [],
      needsReview: false,
      createdBy: payload.createdBy ?? payload.userId,
      softDeleted: false,
      note: payload.note,
      idempotencyKey: payload.idempotencyKey,
    });
    return this.timbratureRepository.save(timbratura);
  }

  async list(dto: ListTimbratureDto) {
    const page = dto.page ?? 1;
    const limit = dto.limit ?? 20;
    const sort = dto.sort ?? 'DESC';

    const [data, total] = await this.timbratureRepository.findAndCount({
      order: { deviceTimestamp: sort },
      skip: (page - 1) * limit,
      take: limit,
    });

    return {
      data,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    };
  }
}
