/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AnomalyFlag = 'DOUBLE_IN' | 'ORPHAN_OUT' | 'FORCED_CLOSE' | 'OVERLAP' | 'FUTURE_TIME' | 'PRE_EMPLOYMENT' | 'OFFLINE_REORDERED' | 'ROLE_VIOLATION' | 'MANUAL_OVERRIDE';

export const AnomalyFlag = {
    DoubleIn: 'DOUBLE_IN' as AnomalyFlag,
    OrphanOut: 'ORPHAN_OUT' as AnomalyFlag,
    ForcedClose: 'FORCED_CLOSE' as AnomalyFlag,
    Overlap: 'OVERLAP' as AnomalyFlag,
    FutureTime: 'FUTURE_TIME' as AnomalyFlag,
    PreEmployment: 'PRE_EMPLOYMENT' as AnomalyFlag,
    OfflineReordered: 'OFFLINE_REORDERED' as AnomalyFlag,
    RoleViolation: 'ROLE_VIOLATION' as AnomalyFlag,
    ManualOverride: 'MANUAL_OVERRIDE' as AnomalyFlag
};

