/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QRCodeRevision { 
    id: string;
    commessaId: string;
    /**
     * QR precedente (invalidato)
     */
    oldCode: string;
    /**
     * Nuovo QR attivo
     */
    newCode: string;
    /**
     * UserId (ADMIN o MANAGER)
     */
    regeneratedBy: string;
    regeneratedAt: string;
    /**
     * Motivo della rigenerazione (es. smarrimento fogli, cambio area, ecc.)
     */
    reason?: string;
    /**
     * IP del richiedente
     */
    ipAddress?: string;
    /**
     * Esito dell\'operazione (false se password errata)
     */
    success?: boolean;
}

