/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnomalyFlag } from './anomalyFlag';
import { ValidityStatus } from './validityStatus';


/**
 * Vista derivata da coppie IN/OUT consecutive sulla stessa commessa
 */
export interface Turno { 
    userId: string;
    commessaId: string;
    startTime: string;
    endTime: string;
    durationMinutes: number;
    validityStatus?: ValidityStatus;
    anomalyFlags?: Array<AnomalyFlag>;
    /**
     * ID delle timbrature che compongono il turno
     */
    sourceTimbrature?: Array<string>;
}
export namespace Turno {
}


