/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface User { 
    id: string;
    /**
     * Matricola o codice interno aziendale univoco
     */
    codiceDipendente: string;
    nome: string;
    cognome?: string;
    email: string;
    ruolo: Role;
    /**
     * Reparto aziendale di appartenenza
     */
    reparto?: string;
    /**
     * Qualifica o mansione (solo informativo)
     */
    qualifica?: string;
    /**
     * Se false, l\'utente non può più timbrare né accedere
     */
    attivo: boolean;
    dataAssunzione: string;
    createdAt: string;
    /**
     * UserId dell\'admin che ha creato l\'account
     */
    createdBy?: string;
    lastLoginAt?: string;
    /**
     * Annotazioni interne (visibili solo ad admin/manager)
     */
    note?: string;
}
export namespace User {
}


