/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface UsersPostRequest { 
    codiceDipendente: string;
    nome: string;
    cognome: string;
    email: string;
    ruolo: Role;
    reparto?: string;
    qualifica?: string;
    dataAssunzione: string;
}
export namespace UsersPostRequest {
}


