/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ValidityStatus = 'OK' | 'AUTO_CORRECTED' | 'CONFLICT' | 'OVERLAP' | 'MISSING_OUT' | 'OFFLINE_INCONSISTENT';

export const ValidityStatus = {
    Ok: 'OK' as ValidityStatus,
    AutoCorrected: 'AUTO_CORRECTED' as ValidityStatus,
    Conflict: 'CONFLICT' as ValidityStatus,
    Overlap: 'OVERLAP' as ValidityStatus,
    MissingOut: 'MISSING_OUT' as ValidityStatus,
    OfflineInconsistent: 'OFFLINE_INCONSISTENT' as ValidityStatus
};

