services:
  postgres:
    image: postgres:16-alpine
    container_name: ss_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: softsignals
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d softsignals']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: ss_redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: .
      args:
        APP_NAME: auth
    env_file:
      - .env.auth
    environment:
      NEST_APP: auth-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3001:3001'

  timbrature-service:
    build:
      context: .
      args:
        APP_NAME: timbrature
    env_file:
      - .env.timbrature
    environment:
      NEST_APP: timbrature-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '3002:3002'

  api-gateway-bff:
    build:
      context: .
      args:
        APP_NAME: gateway
    env_file:
      - .env.gateway
    environment:
      NEST_APP: api-gateway-bff
    depends_on:
      auth-service:
        condition: service_started
      timbrature-service:
        condition: service_started
    ports:
      - '3000:3000'

volumes:
  postgres_data:
