import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

export enum TipoTimbraturaEnum {
  IN = 'IN',
  OUT = 'OUT',
}

export enum OrigineEnum {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  MANUALE = 'MANUALE',
  SISTEMA = 'SISTEMA',
}

export enum ValidityStatusEnum {
  OK = 'OK',
  AUTO_CORRECTED = 'AUTO_CORRECTED',
  CONFLICT = 'CONFLICT',
  OVERLAP = 'OVERLAP',
  MISSING_OUT = 'MISSING_OUT',
  OFFLINE_INCONSISTENT = 'OFFLINE_INCONSISTENT',
}

export enum AnomalyFlagEnum {
  DOUBLE_IN = 'DOUBLE_IN',
  ORPHAN_OUT = 'ORPHAN_OUT',
  FORCED_CLOSE = 'FORCED_CLOSE',
  OVERLAP = 'OVERLAP',
  FUTURE_TIME = 'FUTURE_TIME',
  PRE_EMPLOYMENT = 'PRE_EMPLOYMENT',
  OFFLINE_REORDERED = 'OFFLINE_REORDERED',
  ROLE_VIOLATION = 'ROLE_VIOLATION',
  MANUAL_OVERRIDE = 'MANUAL_OVERRIDE',
}

@Entity('timbrature')
export class TimbraturaEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'user_id' })
  userId: string;

  @Column({ name: 'commessa_id' })
  commessaId: string;

  @Column({
    name: 'tipo',
    type: 'enum',
    enum: TipoTimbraturaEnum,
    enumName: 'tipo_timbratura_enum',
  })
  tipo: TipoTimbraturaEnum;

  @Column({ name: 'device_timestamp', type: 'timestamptz' })
  deviceTimestamp: Date;

  @Column({
    name: 'server_timestamp',
    type: 'timestamptz',
    default: () => 'now()',
  })
  serverTimestamp: Date;

  @Column({
    name: 'origine',
    type: 'enum',
    enum: OrigineEnum,
    enumName: 'origine_enum',
    default: OrigineEnum.ONLINE,
  })
  origine: OrigineEnum;

  @Column({ name: 'auto_generated', default: false })
  autoGenerated: boolean;

  @Column({
    name: 'validity_status',
    type: 'enum',
    enum: ValidityStatusEnum,
    enumName: 'validity_status',
    default: ValidityStatusEnum.OK,
  })
  validityStatus: ValidityStatusEnum;

  @Column({
    name: 'anomaly_flags',
    type: 'enum',
    enum: AnomalyFlagEnum,
    enumName: 'anomaly_flag',
    array: true,
    default: '{}',
  })
  anomalyFlags: AnomalyFlagEnum[];

  @Column({ name: 'needs_review', default: false })
  needsReview: boolean;

  @Column({ name: 'created_by' })
  createdBy: string;

  @Column({ name: 'soft_deleted', default: false })
  softDeleted: boolean;

  @Column({ nullable: true })
  note?: string;

  @Column({ name: 'idempotency_key', nullable: true, unique: true })
  idempotencyKey?: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
