/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { Commessa } from '../model/commessa';
import { CommesseIdPatchRequest } from '../model/commesseIdPatchRequest';
import { CommesseIdQrRegeneratePost200Response } from '../model/commesseIdQrRegeneratePost200Response';
import { CommessePostRequest } from '../model/commessePostRequest';
import { LoginRequest } from '../model/loginRequest';
import { MeResponse } from '../model/meResponse';
import { QRCodeRevision } from '../model/qRCodeRevision';
import { QRRegenerationRequest } from '../model/qRRegenerationRequest';
import { RefreshRequest } from '../model/refreshRequest';
import { RoleHistory } from '../model/roleHistory';
import { Timbratura } from '../model/timbratura';
import { TimbraturaRevision } from '../model/timbraturaRevision';
import { TimbratureIdDeleteRequest } from '../model/timbratureIdDeleteRequest';
import { TimbratureIdPatchRequest } from '../model/timbratureIdPatchRequest';
import { TimbraturePostRequest } from '../model/timbraturePostRequest';
import { TokenPair } from '../model/tokenPair';
import { TurniSummaryGet200Response } from '../model/turniSummaryGet200Response';
import { Turno } from '../model/turno';
import { User } from '../model/user';
import { UsersIdPatchRequest } from '../model/usersIdPatchRequest';
import { UsersIdRolePatchRequest } from '../model/usersIdRolePatchRequest';
import { UsersPostRequest } from '../model/usersPostRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class DefaultService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Login persistente (crea sessione lunga su dispositivo)
     * 
     * @param loginRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authLoginPostOpts.config] Override http request option.
     */
    public authLoginPost(loginRequest: LoginRequest, authLoginPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<TokenPair>>;
    public authLoginPost(loginRequest: LoginRequest, authLoginPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (loginRequest === null || loginRequest === undefined) {
            throw new Error('Required parameter loginRequest was null or undefined when calling authLoginPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<TokenPair>(`${this.basePath}/auth/login`,
                    loginRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authLoginPostOpts?.config,
                        headers: {...headers, ...authLoginPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Logout globale (revoca tutte le sessioni dell\&#39;utente)
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authLogoutAllPostOpts.config] Override http request option.
     */
    public authLogoutAllPost(authLogoutAllPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public authLogoutAllPost(authLogoutAllPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/auth/logout-all`,
                    null,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authLogoutAllPostOpts?.config,
                        headers: {...headers, ...authLogoutAllPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Logout dal dispositivo corrente
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authLogoutPostOpts.config] Override http request option.
     */
    public authLogoutPost(authLogoutPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public authLogoutPost(authLogoutPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/auth/logout`,
                    null,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authLogoutPostOpts?.config,
                        headers: {...headers, ...authLogoutPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Verifica sessione e ritorna profilo
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authMeGetOpts.config] Override http request option.
     */
    public authMeGet(authMeGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<MeResponse>>;
    public authMeGet(authMeGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<MeResponse>(`${this.basePath}/auth/me`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authMeGetOpts?.config,
                        headers: {...headers, ...authMeGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Rinnovo automatico token (rotation + device binding)
     * 
     * @param refreshRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authRefreshPostOpts.config] Override http request option.
     */
    public authRefreshPost(refreshRequest: RefreshRequest, authRefreshPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<TokenPair>>;
    public authRefreshPost(refreshRequest: RefreshRequest, authRefreshPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (refreshRequest === null || refreshRequest === undefined) {
            throw new Error('Required parameter refreshRequest was null or undefined when calling authRefreshPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<TokenPair>(`${this.basePath}/auth/refresh`,
                    refreshRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authRefreshPostOpts?.config,
                        headers: {...headers, ...authRefreshPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Elenco commesse
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [commesseGetOpts.config] Override http request option.
     */
    public commesseGet(commesseGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<Commessa>>>;
    public commesseGet(commesseGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<Commessa>>(`${this.basePath}/commesse`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...commesseGetOpts?.config,
                        headers: {...headers, ...commesseGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Dettaglio singola commessa
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [commesseIdGetOpts.config] Override http request option.
     */
    public commesseIdGet(id: string, commesseIdGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Commessa>>;
    public commesseIdGet(id: string, commesseIdGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling commesseIdGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Commessa>(`${this.basePath}/commesse/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...commesseIdGetOpts?.config,
                        headers: {...headers, ...commesseIdGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Modifica dati commessa (solo ADMIN)
     * 
     * @param id 
     * @param commesseIdPatchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [commesseIdPatchOpts.config] Override http request option.
     */
    public commesseIdPatch(id: string, commesseIdPatchRequest?: CommesseIdPatchRequest, commesseIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Commessa>>;
    public commesseIdPatch(id: string, commesseIdPatchRequest?: CommesseIdPatchRequest, commesseIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling commesseIdPatch.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<Commessa>(`${this.basePath}/commesse/${encodeURIComponent(String(id))}`,
                    commesseIdPatchRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...commesseIdPatchOpts?.config,
                        headers: {...headers, ...commesseIdPatchOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Storico rigenerazioni QR (solo ADMIN)
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [commesseIdQrHistoryGetOpts.config] Override http request option.
     */
    public commesseIdQrHistoryGet(id: string, commesseIdQrHistoryGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<QRCodeRevision>>>;
    public commesseIdQrHistoryGet(id: string, commesseIdQrHistoryGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling commesseIdQrHistoryGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<QRCodeRevision>>(`${this.basePath}/commesse/${encodeURIComponent(String(id))}/qr/history`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...commesseIdQrHistoryGetOpts?.config,
                        headers: {...headers, ...commesseIdQrHistoryGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Rigenera il QR della commessa (ADMIN o MANAGER, password globale)
     * 
     * @param id 
     * @param qRRegenerationRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [commesseIdQrRegeneratePostOpts.config] Override http request option.
     */
    public commesseIdQrRegeneratePost(id: string, qRRegenerationRequest: QRRegenerationRequest, commesseIdQrRegeneratePostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<CommesseIdQrRegeneratePost200Response>>;
    public commesseIdQrRegeneratePost(id: string, qRRegenerationRequest: QRRegenerationRequest, commesseIdQrRegeneratePostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling commesseIdQrRegeneratePost.');
        }

        if (qRRegenerationRequest === null || qRRegenerationRequest === undefined) {
            throw new Error('Required parameter qRRegenerationRequest was null or undefined when calling commesseIdQrRegeneratePost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<CommesseIdQrRegeneratePost200Response>(`${this.basePath}/commesse/${encodeURIComponent(String(id))}/qr/regenerate`,
                    qRRegenerationRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...commesseIdQrRegeneratePostOpts?.config,
                        headers: {...headers, ...commesseIdQrRegeneratePostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Crea una nuova commessa (solo ADMIN)
     * 
     * @param commessePostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [commessePostOpts.config] Override http request option.
     */
    public commessePost(commessePostRequest: CommessePostRequest, commessePostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Commessa>>;
    public commessePost(commessePostRequest: CommessePostRequest, commessePostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (commessePostRequest === null || commessePostRequest === undefined) {
            throw new Error('Required parameter commessePostRequest was null or undefined when calling commessePost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<Commessa>(`${this.basePath}/commesse`,
                    commessePostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...commessePostOpts?.config,
                        headers: {...headers, ...commessePostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Elenco timbrature con filtri
     * 
     * @param userId 
     * @param commessaId 
     * @param _from 
     * @param to 
     * @param includeConflicts 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [timbratureGetOpts.config] Override http request option.
     */
    public timbratureGet(userId?: string, commessaId?: string, _from?: string, to?: string, includeConflicts?: boolean, timbratureGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<Timbratura>>>;
    public timbratureGet(userId?: string, commessaId?: string, _from?: string, to?: string, includeConflicts?: boolean, timbratureGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (userId !== undefined && userId !== null) {
            queryParameters.append('userId', <any>userId);
        }
        if (commessaId !== undefined && commessaId !== null) {
            queryParameters.append('commessaId', <any>commessaId);
        }
        if (_from !== undefined && _from !== null) {
            queryParameters.append('from', <any>_from);
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', <any>to);
        }
        if (includeConflicts !== undefined && includeConflicts !== null) {
            queryParameters.append('includeConflicts', <any>includeConflicts);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<Timbratura>>(`${this.basePath}/timbrature`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...timbratureGetOpts?.config,
                        headers: {...headers, ...timbratureGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Annulla una timbratura (soft delete, audit obbligatorio)
     * 
     * @param id 
     * @param timbratureIdDeleteRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [timbratureIdDeleteOpts.config] Override http request option.
     */
    public timbratureIdDelete(id: string, timbratureIdDeleteRequest: TimbratureIdDeleteRequest, timbratureIdDeleteOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Timbratura>>;
    public timbratureIdDelete(id: string, timbratureIdDeleteRequest: TimbratureIdDeleteRequest, timbratureIdDeleteOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling timbratureIdDelete.');
        }

        if (timbratureIdDeleteRequest === null || timbratureIdDeleteRequest === undefined) {
            throw new Error('Required parameter timbratureIdDeleteRequest was null or undefined when calling timbratureIdDelete.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<Timbratura>(`${this.basePath}/timbrature/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...timbratureIdDeleteOpts?.config,
                        headers: {...headers, ...timbratureIdDeleteOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Modifica una timbratura (solo manager/admin, mai su se stessi se manager)
     * 
     * @param id 
     * @param timbratureIdPatchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [timbratureIdPatchOpts.config] Override http request option.
     */
    public timbratureIdPatch(id: string, timbratureIdPatchRequest: TimbratureIdPatchRequest, timbratureIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Timbratura>>;
    public timbratureIdPatch(id: string, timbratureIdPatchRequest: TimbratureIdPatchRequest, timbratureIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling timbratureIdPatch.');
        }

        if (timbratureIdPatchRequest === null || timbratureIdPatchRequest === undefined) {
            throw new Error('Required parameter timbratureIdPatchRequest was null or undefined when calling timbratureIdPatch.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<Timbratura>(`${this.basePath}/timbrature/${encodeURIComponent(String(id))}`,
                    timbratureIdPatchRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...timbratureIdPatchOpts?.config,
                        headers: {...headers, ...timbratureIdPatchOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Storico modifiche di una timbratura (solo admin/manager)
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [timbratureIdRevisionsGetOpts.config] Override http request option.
     */
    public timbratureIdRevisionsGet(id: string, timbratureIdRevisionsGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<TimbraturaRevision>>>;
    public timbratureIdRevisionsGet(id: string, timbratureIdRevisionsGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling timbratureIdRevisionsGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<TimbraturaRevision>>(`${this.basePath}/timbrature/${encodeURIComponent(String(id))}/revisions`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...timbratureIdRevisionsGetOpts?.config,
                        headers: {...headers, ...timbratureIdRevisionsGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Registra una nuova timbratura (IN/OUT, online o offline, anche via QR)
     * 
     * @param timbraturePostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [timbraturePostOpts.config] Override http request option.
     */
    public timbraturePost(timbraturePostRequest: TimbraturePostRequest, timbraturePostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Timbratura>>;
    public timbraturePost(timbraturePostRequest: TimbraturePostRequest, timbraturePostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (timbraturePostRequest === null || timbraturePostRequest === undefined) {
            throw new Error('Required parameter timbraturePostRequest was null or undefined when calling timbraturePost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<Timbratura>(`${this.basePath}/timbrature`,
                    timbraturePostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...timbraturePostOpts?.config,
                        headers: {...headers, ...timbraturePostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Restituisce i turni logici (accoppiamento IN-OUT) per utente/commessa/periodo
     * I turni sono derivati dalle timbrature. Per default vengono esclusi quelli con validityStatus &#x3D; CONFLICT. 
     * @param userId Filtra per dipendente
     * @param commessaId Filtra per commessa
     * @param _from 
     * @param to 
     * @param includeConflicts Include anche turni con anomalie gravi
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [turniGetOpts.config] Override http request option.
     */
    public turniGet(userId?: string, commessaId?: string, _from?: string, to?: string, includeConflicts?: boolean, turniGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<Turno>>>;
    public turniGet(userId?: string, commessaId?: string, _from?: string, to?: string, includeConflicts?: boolean, turniGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (userId !== undefined && userId !== null) {
            queryParameters.append('userId', <any>userId);
        }
        if (commessaId !== undefined && commessaId !== null) {
            queryParameters.append('commessaId', <any>commessaId);
        }
        if (_from !== undefined && _from !== null) {
            queryParameters.append('from', <any>_from);
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', <any>to);
        }
        if (includeConflicts !== undefined && includeConflicts !== null) {
            queryParameters.append('includeConflicts', <any>includeConflicts);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<Turno>>(`${this.basePath}/turni`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...turniGetOpts?.config,
                        headers: {...headers, ...turniGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Riepilogo ore lavorate per periodo, giorno, reparto
     * 
     * @param userId 
     * @param commessaId 
     * @param reparto 
     * @param _from 
     * @param to 
     * @param groupBy 
     * @param includeConflicts 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [turniSummaryGetOpts.config] Override http request option.
     */
    public turniSummaryGet(userId?: string, commessaId?: string, reparto?: string, _from?: string, to?: string, groupBy?: 'DAY' | 'USER' | 'COMMESSA' | 'REPARTO', includeConflicts?: boolean, turniSummaryGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<TurniSummaryGet200Response>>;
    public turniSummaryGet(userId?: string, commessaId?: string, reparto?: string, _from?: string, to?: string, groupBy?: 'DAY' | 'USER' | 'COMMESSA' | 'REPARTO', includeConflicts?: boolean, turniSummaryGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (userId !== undefined && userId !== null) {
            queryParameters.append('userId', <any>userId);
        }
        if (commessaId !== undefined && commessaId !== null) {
            queryParameters.append('commessaId', <any>commessaId);
        }
        if (reparto !== undefined && reparto !== null) {
            queryParameters.append('reparto', <any>reparto);
        }
        if (_from !== undefined && _from !== null) {
            queryParameters.append('from', <any>_from);
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', <any>to);
        }
        if (groupBy !== undefined && groupBy !== null) {
            queryParameters.append('groupBy', <any>groupBy);
        }
        if (includeConflicts !== undefined && includeConflicts !== null) {
            queryParameters.append('includeConflicts', <any>includeConflicts);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<TurniSummaryGet200Response>(`${this.basePath}/turni/summary`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...turniSummaryGetOpts?.config,
                        headers: {...headers, ...turniSummaryGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Dettaglio di un singolo turno logico
     * Usato dall\&#39;interfaccia manager per ispezionare e correggere un turno specifico
     * @param turnoId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [turniTurnoIdGetOpts.config] Override http request option.
     */
    public turniTurnoIdGet(turnoId: string, turniTurnoIdGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Turno>>;
    public turniTurnoIdGet(turnoId: string, turniTurnoIdGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (turnoId === null || turnoId === undefined) {
            throw new Error('Required parameter turnoId was null or undefined when calling turniTurnoIdGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Turno>(`${this.basePath}/turni/${encodeURIComponent(String(turnoId))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...turniTurnoIdGetOpts?.config,
                        headers: {...headers, ...turniTurnoIdGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Elenco utenti
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersGetOpts.config] Override http request option.
     */
    public usersGet(usersGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<User>>>;
    public usersGet(usersGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<User>>(`${this.basePath}/users`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersGetOpts?.config,
                        headers: {...headers, ...usersGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Disattiva un utente (solo ADMIN)
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersIdDeactivatePostOpts.config] Override http request option.
     */
    public usersIdDeactivatePost(id: string, usersIdDeactivatePostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<User>>;
    public usersIdDeactivatePost(id: string, usersIdDeactivatePostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling usersIdDeactivatePost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<User>(`${this.basePath}/users/${encodeURIComponent(String(id))}/deactivate`,
                    null,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersIdDeactivatePostOpts?.config,
                        headers: {...headers, ...usersIdDeactivatePostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Modifica dati anagrafici utente (solo ADMIN)
     * 
     * @param id 
     * @param usersIdPatchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersIdPatchOpts.config] Override http request option.
     */
    public usersIdPatch(id: string, usersIdPatchRequest?: UsersIdPatchRequest, usersIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<User>>;
    public usersIdPatch(id: string, usersIdPatchRequest?: UsersIdPatchRequest, usersIdPatchOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling usersIdPatch.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<User>(`${this.basePath}/users/${encodeURIComponent(String(id))}`,
                    usersIdPatchRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersIdPatchOpts?.config,
                        headers: {...headers, ...usersIdPatchOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Storico cambi ruolo di un utente (solo ADMIN)
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersIdRoleHistoryGetOpts.config] Override http request option.
     */
    public usersIdRoleHistoryGet(id: string, usersIdRoleHistoryGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<RoleHistory>>>;
    public usersIdRoleHistoryGet(id: string, usersIdRoleHistoryGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling usersIdRoleHistoryGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<RoleHistory>>(`${this.basePath}/users/${encodeURIComponent(String(id))}/role-history`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersIdRoleHistoryGetOpts?.config,
                        headers: {...headers, ...usersIdRoleHistoryGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Cambia ruolo a un utente (solo ADMIN, mai su se stesso)
     * 
     * @param id 
     * @param usersIdRolePatchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersIdRolePatchOpts.config] Override http request option.
     */
    public usersIdRolePatch(id: string, usersIdRolePatchRequest: UsersIdRolePatchRequest, usersIdRolePatchOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<User>>;
    public usersIdRolePatch(id: string, usersIdRolePatchRequest: UsersIdRolePatchRequest, usersIdRolePatchOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling usersIdRolePatch.');
        }

        if (usersIdRolePatchRequest === null || usersIdRolePatchRequest === undefined) {
            throw new Error('Required parameter usersIdRolePatchRequest was null or undefined when calling usersIdRolePatch.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<User>(`${this.basePath}/users/${encodeURIComponent(String(id))}/role`,
                    usersIdRolePatchRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersIdRolePatchOpts?.config,
                        headers: {...headers, ...usersIdRolePatchOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Crea un nuovo utente (solo ADMIN)
     * 
     * @param usersPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersPostOpts.config] Override http request option.
     */
    public usersPost(usersPostRequest: UsersPostRequest, usersPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<User>>;
    public usersPost(usersPostRequest: UsersPostRequest, usersPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (usersPostRequest === null || usersPostRequest === undefined) {
            throw new Error('Required parameter usersPostRequest was null or undefined when calling usersPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<User>(`${this.basePath}/users`,
                    usersPostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersPostOpts?.config,
                        headers: {...headers, ...usersPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
