/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Commessa { 
    id: string;
    nome: string;
    descrizione?: string;
    /**
     * Token attualmente valido per la timbratura (codificato nel QR)
     */
    codiceQRAttivo: string;
    /**
     * Se false, la commessa non accetta nuove timbrature
     */
    attiva: boolean;
    createdAt: string;
    /**
     * UserId che ha creato la commessa
     */
    createdBy?: string;
}

