/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Role = 'ADMIN' | 'MANAGER' | 'DIPENDENTE';

export const Role = {
    Admin: 'ADMIN' as Role,
    Manager: 'MANAGER' as Role,
    Dipendente: 'DIPENDENTE' as Role
};

