/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface RoleHistory { 
    id: string;
    userId: string;
    oldRole: Role;
    newRole: Role;
    /**
     * UserId dell\'ADMIN che ha effettuato il cambio
     */
    changedBy: string;
    changedAt: string;
    /**
     * Motivo del cambio ruolo
     */
    reason?: string;
    /**
     * IP da cui è stato effettuato il cambio
     */
    ipAddress?: string;
}
export namespace RoleHistory {
}


