/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnomalyFlag } from './anomalyFlag';
import { ValidityStatus } from './validityStatus';


export interface Timbratura { 
    id: string;
    userId: string;
    commessaId: string;
    tipo: Timbratura.TipoEnum;
    /**
     * Timestamp generato dal dispositivo
     */
    deviceTimestamp: string;
    /**
     * Timestamp di ricezione sul server
     */
    serverTimestamp: string;
    origine: Timbratura.OrigineEnum;
    /**
     * True se generata automaticamente (es. OUT forzato)
     */
    autoGenerated?: boolean;
    validityStatus: ValidityStatus;
    anomalyFlags?: Array<AnomalyFlag>;
    needsReview?: boolean;
    /**
     * userId o SYSTEM
     */
    createdBy?: string;
    /**
     * True se annullata (mai cancellata fisicamente)
     */
    softDeleted?: boolean;
}
export namespace Timbratura {
    export type TipoEnum = 'IN' | 'OUT';
    export const TipoEnum = {
        In: 'IN' as TipoEnum,
        Out: 'OUT' as TipoEnum
    };
    export type OrigineEnum = 'ONLINE' | 'OFFLINE' | 'MANUALE' | 'SISTEMA';
    export const OrigineEnum = {
        Online: 'ONLINE' as OrigineEnum,
        Offline: 'OFFLINE' as OrigineEnum,
        Manuale: 'MANUALE' as OrigineEnum,
        Sistema: 'SISTEMA' as OrigineEnum
    };
}


