/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimbraturePostRequest { 
    tipo: TimbraturePostRequest.TipoEnum;
    commessaId: string;
    deviceTimestamp: string;
    origine?: TimbraturePostRequest.OrigineEnum;
    /**
     * Presente solo se origine = QR
     */
    qrToken?: string;
}
export namespace TimbraturePostRequest {
    export type TipoEnum = 'IN' | 'OUT';
    export const TipoEnum = {
        In: 'IN' as TipoEnum,
        Out: 'OUT' as TipoEnum
    };
    export type OrigineEnum = 'ONLINE' | 'OFFLINE' | 'QR';
    export const OrigineEnum = {
        Online: 'ONLINE' as OrigineEnum,
        Offline: 'OFFLINE' as OrigineEnum,
        Qr: 'QR' as OrigineEnum
    };
}


