/**
 * API Sistema Timbrature
 * API per la gestione delle timbrature, turni, commesse e utenti
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimbraturaRevision { 
    id: string;
    timbraturaId: string;
    /**
     * Snapshot precedente
     */
    oldValue?: object;
    /**
     * Snapshot successivo
     */
    newValue?: object;
    /**
     * userId o SYSTEM
     */
    modifiedBy: string;
    modificationType: TimbraturaRevision.ModificationTypeEnum;
    /**
     * Codice regola (es. R2_FORCED_CLOSE)
     */
    ruleApplied?: string;
    reason?: string;
    timestamp: string;
}
export namespace TimbraturaRevision {
    export type ModificationTypeEnum = 'MANUAL' | 'AUTO_CORRECTION';
    export const ModificationTypeEnum = {
        Manual: 'MANUAL' as ModificationTypeEnum,
        AutoCorrection: 'AUTO_CORRECTION' as ModificationTypeEnum
    };
}


